<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>dev.gruff.hardstop</groupId>
  <artifactId>cachegenie</artifactId>
  <version>0.0.1</version>
  <packaging>pom</packaging>
  <modules>
    <module>streamer</module>
    <module>core</module>
    <module>viewer</module>
    <module>cli</module>
    <module>release</module>
  </modules>


  <properties>
    <compiler-plugin.version>3.13.0</compiler-plugin.version>

    <maven-resolver.version>1.9.21</maven-resolver.version>

    <maven.compiler.source>22</maven.compiler.source>
    <maven.compiler.target>22</maven.compiler.target>
    <maven.compiler.release>22</maven.compiler.release>
    <maven.version>3.6.0</maven.version>
    <exec.mainClass>dev.gruff.hardstop.cachegenie.cli.Main</exec.mainClass>

    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

    <skipITs>true</skipITs>
    <surefire-plugin.version>3.3.1</surefire-plugin.version>
    <duckdb.version>1.5.4.0</duckdb.version>



  </properties>



  <dependencyManagement>
    <dependencies>
      <dependency>
          <groupId>dev.gruff.hardstop</groupId>
          <artifactId>cachegenie-core</artifactId>
          <version>${project.version}</version>
      </dependency>
      <dependency>
          <groupId>dev.gruff.hardstop</groupId>
          <artifactId>streamer</artifactId>
          <version>${project.version}</version>
      </dependency>
      <dependency>
          <groupId>dev.gruff.hardstop</groupId>
          <artifactId>cli</artifactId>
          <version>${project.version}</version>
      </dependency>
      <dependency>
          <groupId>dev.gruff.hardstop</groupId>
          <artifactId>viewer</artifactId>
          <version>${project.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>2.0.13</version>
    </dependency>

    <dependency>
      <groupId>info.picocli</groupId>
      <artifactId>picocli</artifactId>
      <version>4.7.6</version>
    </dependency>

    <dependency>
      <groupId>org.jsoup</groupId>
      <artifactId>jsoup</artifactId>
      <version>1.17.2</version>
    </dependency>

    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13.2</version>
      <scope>test</scope>
    </dependency>

  <dependency>
    <groupId>org.apache.maven.resolver</groupId>
    <artifactId>maven-resolver-api</artifactId>
    <version>${maven-resolver.version}</version>
  </dependency>

  <dependency>
    <groupId>org.apache.maven.resolver</groupId>
    <artifactId>maven-resolver-spi</artifactId>
    <version>${maven-resolver.version}</version>
  </dependency>

  <dependency>
    <groupId>org.apache.maven.resolver</groupId>
    <artifactId>maven-resolver-util</artifactId>
    <version>${maven-resolver.version}</version>
  </dependency>

  <dependency>
    <groupId>org.apache.maven.resolver</groupId>
    <artifactId>maven-resolver-impl</artifactId>
    <version>${maven-resolver.version}</version>
  </dependency>

  <dependency>
    <groupId>org.apache.maven.resolver</groupId>
    <artifactId>maven-resolver-connector-basic</artifactId>
    <version>${maven-resolver.version}</version>
  </dependency>

  <dependency>
    <groupId>org.apache.maven.resolver</groupId>
    <artifactId>maven-resolver-transport-file</artifactId>
    <version>${maven-resolver.version}</version>
  </dependency>

  <dependency>
    <groupId>org.apache.maven.resolver</groupId>
    <artifactId>maven-resolver-transport-http</artifactId>
    <version>${maven-resolver.version}</version>
  </dependency>



  <dependency>
    <groupId>org.apache.maven</groupId>
    <artifactId>maven-resolver-provider</artifactId>
    <version>${maven.version}</version>
  </dependency>

  <dependency>
    <groupId>ch.qos.logback</groupId>
    <artifactId>logback-classic</artifactId>
    <version>1.5.6</version>
  </dependency>

  <dependency>
    <groupId>org.duckdb</groupId>
    <artifactId>duckdb_jdbc</artifactId>
    <version>${duckdb.version}</version>
  </dependency>

</dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${compiler-plugin.version}</version>
        <configuration>
          <release>${maven.compiler.release}</release>
        </configuration>
      </plugin>
    </plugins>
  </build>




</project>
