quarkus.banner.enabled=false
quarkus.log.file.enable=true
%prod.quarkus.log.file.path=.cachegenie.log
%dev.quarkus.log.file.path=target/cachegenie.log
quarkus.log.file.level=INFO
#quarkus.package.type=uber-jar